#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  1 11:05:36 2025

@author: epoirier1
"""

import pyrsktools as pyrsk
import matplotlib.pyplot as plt

with pyrsk.RSK("/home/epoirier1/Documents/PROJETS/2025/Proc_RBR_Somlit/rawdata/sample.rsk") as rsk:
    
    # Read data
    rsk.readdata()
    
    rsk.plotdata(channels=["pressure"], profile = 2, direction = "down")
    rsk.plotdata(channels=["pressure"], profile = 2, direction = "up")
    plt.show()
    
   
    
 
    #bin average on depth 0.25dbar or 25 cm
    #the binning processus is corrupting the showing of upcast
    rsk.binaverage(
        binBy = "pressure",
        binSize = 1,
        boundary = [5,300], # 0.5 is the min pressure starting the binning and 10 the max
        direction = "down"
        )
    rsk.readprocesseddata()
    
    rsk.binaverage(
        binBy = "pressure",
        binSize = 1,
        boundary = [5,300], # 0.5 is the min pressure starting the binning and 10 the max
        direction = "up"
        )

    
    # Plot a few profiles of temperature, conductivity, and chlorophyll
    fig, axes = rsk.plotprofiles(
        channels=["temperature"],
        profiles=2,
        direction="both",
        reference='pressure'
        )
    plt.show()